Feat: 도메인 모듈 분리
NOWSOPT34-Advanced-Study/Team3 pull request #2
Opened 2024-04-21 12:29 UTC by m6z1

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #1 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 도메인 모듈 분리해서 기존에 앱 단에 있던 도메인 로직 파일을 도메인 모듈로 이동시켰습니다.
- `Paging`,`Coroutines`, `Hilt-compiler` 라이브러리 도메인에 추가했습니다.

- app 단의 `build.gradle` 에 하단의 코드가 추가되어있습니다. 
<img width="630" alt="스크린샷 2024-04-21 오후 9 18 47" src="https://github.com/NOWSOPT34-Advanced-Study/Team3/assets/114990782/b76a1b1a-4fea-470b-bcf2-fc1c9a190733">

이 코드를 추가한 이유는 packaging 코드를 추가하지 않았을 때 아래의 에러가 떴습니다.

<img width="866" alt="스크린샷 2024-04-21 오후 9 19 31" src="https://github.com/NOWSOPT34-Advanced-Study/Team3/assets/114990782/56c8c0fe-2ac9-450e-a087-45c6cb63335c">

[스택오버플로우](https://stackoverflow.com/questions/74944039/android-2-files-found-with-path-meta-inf-gradle-incremental-annotation-processo) 를 보고 해결했습니다.
Dagger와 Hilt 같은 라이브러리를 사용할 때 발생하며, 두 라이브러리의 컴파일러가 동일한 메타데이터 파일을 생성하기 때문에 일어난다고 합니다. 일단은 임시방편으로 넣어서 해결해둔 것이긴 한데! 혹시나 다른 방법있으시다면 .. 공유 부탁드립니다. 

---

**Domain 모듈에서 `Coroutines` 라이브러리가 필요한 이유**

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
[Screen_recording_20240421_211520 (1).webm](https://github.com/NOWSOPT34-Advanced-Study/Team3/assets/114990782/05cf9be3-b0bd-4236-892f-12f9b4f74ba3)

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-04-21 12:41 UTC, chanubc requested changes
한번 확인해 주세요!

2024-04-21 12:41 UTC, chanubc commented on domain/build.gradle.kts
> +    implementation(libs.dagger.hilt.compiler)
// dagger hilt
    implementation(libs.dagger.hilt)
    kapt(libs.dagger.hilt.compiler)
    
    이거 추가해 보시겠어요? 그리고 위에  
    excludes += "/META-INF/{AL2.0,LGPL2.1}"
    excludes += "/META-
    코드 제거 하고 한번 돌려봐주세요!

2024-04-21 16:04 UTC, chanubc approved these changes
진짜 깔끔하게 옮기셨네요 고생하셨습니다!

2024-04-21 16:04 UTC, chanubc commented on domain/build.gradle.kts
> +    implementation(libs.inject)
조아요!!

2024-04-21 16:04 UTC, chanubc commented on domain/build.gradle.kts
> +    id("java-library")
```suggestion
    `java-library`
```
이렇게도 쓸수 있어요!

2024-04-22 02:40 UTC, m6z1 commented on domain/build.gradle.kts
> +    id("java-library")
이 부분도 한 번 공부해봐야겠군요

2024-04-22 02:40 UTC, merged