Feat: Feature 모듈 분리
NOWSOPT34-Advanced-Study/Team3 pull request #3
Opened 2024-04-21 13:03 UTC by Eonji-sw

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- feature 모듈 분리해서 기존에 앱 단에 있던 feature 로직 파일을 feature 모듈로 이동시켰습니다.
- 아래와 같이 의존하는 domain과 core는 제 브랜치 기준 분리가 안되어있으므로 import되지 않아도 그냥 놨뒀습니다. merge 하고 바꾸는게 맞다고 생각해서요.
<img width="513" alt="스크린샷 2024-04-21 오후 10 01 55" src="https://github.com/NOWSOPT34-Advanced-Study/Team3/assets/85453429/8962c095-6b48-47c6-b43e-99998fe2711f">

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴

2024-04-21 14:14 UTC, chanubc requested changes
옮겨 오면서 패키지 명이 바뀌는 거 같은데 확인해주시겠나요?

2024-04-21 14:14 UTC, chanubc commented on feature/src/main/java/com/kotlin/feature/util/DateUtils.kt
> +package com.kotlin.feature.util
전체적으로 패키지 명이 바뀌었는데 한번 확인해주세요!

2024-04-21 16:00 UTC, chanubc commented on feature/src/main/java/com/kotlin/feature/util/DateUtils.kt
> +package com.kotlin.feature.util
com.sopt.now로 패키지명 통일하겠습니다!
근데 상관없는거 같아요

2024-04-21 16:53 UTC, Eonji-sw commented on feature/src/main/java/com/kotlin/feature/util/DateUtils.kt
> +package com.kotlin.feature.util
변경했어요오오오오오

2024-04-21 17:28 UTC, chanubc approved these changes
번거로우 셨을텐데 고생하셨습니다!
사실 복붙하기 편하라고 패키지명 통일을 부탁.. (읍읍..)

2024-04-22 02:43 UTC, m6z1 approved these changes
노가다 작업일 텐데 고생하셨어요 짱

2024-04-22 06:16 UTC, cacaocoffee commented
바쁜 기간에 고생하셨어요!

2024-04-22 06:30 UTC, merged